(* DO NOT EDIT THIS FILE *)
(*let check_init_state : Yojson.Basic.json -> State.state = State.init_state
let check_win_score : State.state -> int = State.win_score
let check_score : State.state -> int = State.score
let check_turns : State.state -> int = State.turns
let check_current_room_id : State.state -> string = State.current_room_id
let check_inv : State.state -> string list = State.inv
let check_visited : State.state -> string list = State.visited
let check_locations : State.state -> (string*string) list = State.locations
let check_do' : Command.command -> State.state -> State.state = State.do'
let check_parse : string -> Command.command = Command.parse*)
